apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgm-nginx-deployment
spec:
  selector:
    matchLabels:
      app: mgm-nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: mgm-nginx
    spec:
      containers:
      - name: megham-nginx
        image: nginx:1.17.3
        ports:
        - containerPort: 80
