#-----------------------------------------------------------------------------------------
#DOCKER COMPOSE - To build & host a custom drupal content mgmt server with a postgres db.
#-----------------------------------------------------------------------------------------
version: '3.8'

services: 
    drupal-server:
        image: drupal-custom
        build: 
            context: .
            dockerfile: 'drupal.Dockerfile'
        #build: . #if the docker filename is blank [Dockerfile]
        volumes:
            - drupal-modules:/var/www/html/modules
            - drupal-profiles:/var/www/html/profiles
            - drupal-themes:/var/www/html/themes
            - drupal-sites:/var/www/html/sites
        ports: 
            - 8086:80
            - 8087:80

    postgres-db: #this is the hostname used for connection
        image: postgres:13
        environment:
            POSTGRES_DB: drupal-db #this is the database name
            POSTGRES_USER: murugan
            POSTGRES_PASSWORD: murugan123
        volumes:
            - drupal-pgdata:/var/lib/postgresql/data 

volumes:
    drupal-modules:
    drupal-profiles:
    drupal-themes:
    drupal-sites:
    drupal-pgdata: