#-----------------------------------------------------------------------------------------
#DOCKER COMPOSE - To host drupal content mgmt server with a postgres as the db.
#-----------------------------------------------------------------------------------------
version: '3.8'

services: 
    drupal-server:
        image: drupal:8.2
        volumes:
            - drupal-modules:/var/www/html/modules
            - drupal-profiles:/var/www/html/profiles
            - drupal-themes:/var/www/html/themes
            - drupal-sites:/var/www/html/sites
        ports: 
            - 8086:80
        
    postgres-db: #this is the hostname used for connection
        image: postgres:13
        ports:
            - 5002:5432
        environment:
            POSTGRES_DB: drupal-db #this is the database name
            POSTGRES_PASSWORD_FILE: /run/secrets/pssql_pswd_3
            POSTGRES_USER_FILE: /run/secrets/pssql_usr
        secrets:
            - pssql_usr
            - pssql_pswd_3
        volumes:
            - drupal-pgdata:/var/lib/postgresql/data 

secrets:
    pssql_usr:
        file: ./pssql_user.txt
    pssql_pswd_3:
        external: true

volumes:
    drupal-modules:
    drupal-profiles:
    drupal-themes:
    drupal-sites:
    drupal-pgdata: